version: "3"
services:
    roulette-webserver:
        build:
            context: .
        ports:
            - "80:80"
        volumes:
            - "./ops/docker/php/xdebug.ini:/etc/php7/conf.d/02_xdebug.ini"
            - ./:/opt/roulette/app

    roulette-database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
        ports:
            - "33061:3306"

    roulette-redis:
        image: redis:3
        ports:
            - "63791:6379"
