#!/usr/bin/env php
<?php

// anything from the container should be available here beause we're using the code from app.php
require __DIR__ . '/bootstrap/app.php';

$kernel = new Roulette\Console\Kernel;

$console = new Roulette\Console\Console($app);
$console->boot($kernel);

$console->run();
